### ISSUE TITLE
在地狱或末地玩家死亡崩服

### ISSUE THREAD

**Issue by 347180440** [Era4FunMC/DirtyMolia#4]
[18:21:02 INFO]: Li_HuaJian issued server command: /kill Li_HuaJian
[18:21:02 INFO]: [Li_HuaJian: Killed Li_HuaJian]
[18:21:02 INFO]: Li_HuaJian was killed
[18:21:03 ERROR]: [io.papermc.paper.threadedregions.TickRegionScheduler] Region #1 centered at chunk [-24, -63] in world 'world' failed to tick:
java.lang.IllegalStateException: World mismatch: expected world_the_end but got world
        at net.minecraft.world.level.Level.getCurrentWorldData(Level.java:222) ~[?:?]
        at net.minecraft.world.entity.Entity.lambda$placeInAsync$6(Entity.java:3843) ~[molia-1.20.2.jar:git-Molia-"81f14dd"]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504) ~[molia-1.20.2.jar:git-Molia-"81f14dd"]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434) ~[molia-1.20.2.jar:git-Molia-"81f14dd"]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263) ~[molia-1.20.2.jar:git-Molia-"81f14dd"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1510) ~[molia-1.20.2.jar:git-Molia-"81f14dd"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:449) ~[molia-1.20.2.jar:git-Molia-"81f14dd"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:406) ~[molia-1.20.2.jar:git-Molia-"81f14dd"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[molia-1.20.2.jar:git-Molia-"81f14dd"]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[18:21:03 INFO]: [RegionShutdownThread] Awaiting scheduler termination for 60s
[18:21:03 INFO]: [RegionShutdownThread] Scheduler halted
[18:21:03 INFO]: Stopping server

重新进入服务器后 复活在当前世界 比如死在末地 崩了  服务器重启了 重进服务器 后复活在末地

**Comment by MrHua269** [comment]
试试77e905155bab330285c6e33ab783c24112f230aa这个提交()
