### ISSUE TITLE
未知的报错 RAM在增加

### ISSUE THREAD

**Issue by 347180440** [Era4FunMC/DirtyMolia#9]
[03:08:18 ERROR]: Thread Region Scheduler Thread #3 failed main thread check: Cannot read world asynchronously
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:60) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlock.getNMS(CraftBlock.java:80) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:239) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlockStates.getBlockState(CraftBlockStates.java:231) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at org.bukkit.craftbukkit.v1_20_R2.block.CraftBlock.getState(CraftBlock.java:343) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at me.spartacus04.jext.listener.RecordPacketListener.onPacketSending(RecordPacketListener.kt:47) ~[JEXT-Reborn_1.2.8.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:219) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeUnpackedPacketSending(SortedPacketListenerList.java:204) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:139) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:100) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:553) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:456) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:467) ~[?:?]
        at net.minecraft.network.Connection$PacketSendAction.lambda$new$0(Connection.java:1046) ~[?:?]
        at net.minecraft.network.Connection$WrappedConsumer.accept(Connection.java:1030) ~[?:?]
        at net.minecraft.network.Connection.processQueue(Connection.java:598) ~[?:?]
        at net.minecraft.network.Connection.flushQueue(Connection.java:555) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:446) ~[?:?]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:245) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:230) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.sendServerPacket(NettyChannelInjector.java:285) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.lambda$processOutbound$6(NettyChannelInjector.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.scheduler.FoliaScheduler.lambda$runTask$1(FoliaScheduler.java:51) ~[ProtocolLib.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[molia-1.20.2.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[molia-1.20.2.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:299) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:154) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:406) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:540) ~[molia-1.20.2.jar:git-Molia-"38ff6a5"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
![image](https://github.com/Era4FunMC/DirtyMolia/assets/107541071/88e51a44-d85d-498c-9aac-8abb04fde5f7)

**Comment by 347180440** [comment]
![image](https://github.com/Era4FunMC/DirtyMolia/assets/107541071/02f65be0-ad27-4b34-8524-a6a83829669b)
重启一次在观察 貌似是 ram值慢慢变高 算正常吗

**Comment by 347180440** [comment]
![image](https://github.com/Era4FunMC/DirtyMolia/assets/107541071/d2927298-8669-4045-9c6b-046a586c810a)
